name: Linux CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      shell: bash
      run: |
          sudo apt-get install ninja-build
    - name: Configure
      shell: bash
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_TESTS=ON
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
    - name: Test
      shell: bash
      run: |
          cd build
          ./test/test_samurai_lib
