name: Linux CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.6
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: samurai-env
        environment-file: conda/environment.yml
    - name: Dependencies
      shell: bash
      run: |
          sudo apt-get install ninja-build
    - name: conda
      shell: bash -l {0}
      run: |
          conda info
          conda list
    - name: Configure
      shell: bash -l {0}
      run: |
          which cmake
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_TESTS=ON
    - name: Build
      shell: bash -l {0}
      run: |
          ls build/_deps
          cmake --build build --target all
    - name: Test
      shell: bash -l {0}
      run: |
          cd build
          ./test/test_samurai_lib
