name: Linux CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp-version: [g++-7, g++-8, g++-9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup compiler and dependencies
        shell: bash
        run: |
            sudo apt install ${{ matrix.cpp-version }} ninja-build
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: samurai-env
          environment-file: conda/environment.yml
      - name: Conda informations
        shell: bash -l {0}
        run: |
            conda info
            conda list
      - name: Configure
        shell: bash -l {0}
        run: |
            export LDFLAGS="${LDFLAGS} -L$CONDA_PREFIX/lib"
            CXX=${{ matrix.cpp-version }} cmake \
                . \
                -Bbuild \
                -GNinja \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTS=ON
      - name: Build
        shell: bash -l {0}
        run: |
            cmake --build build --target all
      - name: Test
        shell: bash -l {0}
        run: |
            export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
            cd build
            ./test/test_samurai_lib
